#!/bin/bash
# ─── WaxLab build script ──────────────────────────────────────────────────────
# Runs on Netlify at deploy time.
# Writes Netlify environment variables into config.js so the browser app can
# read them at runtime via window.WAXLAB_CONFIG.
#
# To test locally:
#   export SUPABASE_URL="https://your-project.supabase.co"
#   export SUPABASE_ANON_KEY="your-anon-key"
#   bash build.sh
# Then open index.html in your browser.

set -e

echo "→ Writing config.js from environment variables..."

cat > config.js << EOF
// Auto-generated by build.sh — do not edit manually.
// This file is created fresh on every Netlify deploy from environment variables.
window.WAXLAB_CONFIG = {
  SUPABASE_URL:      "${SUPABASE_URL:-}",
  SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY:-}",
  GOOGLE_CLIENT_ID:  "${GOOGLE_CLIENT_ID:-}"
};
EOF

# Validate that credentials were actually provided
if [ -z "${SUPABASE_URL}" ] || [ "${SUPABASE_URL}" = "" ]; then
  echo "⚠  WARNING: SUPABASE_URL is not set."
  echo "   App will run in localStorage-only mode (no multi-device sync)."
  echo "   Add SUPABASE_URL in Netlify → Site settings → Environment variables."
fi

if [ -z "${SUPABASE_ANON_KEY}" ] || [ "${SUPABASE_ANON_KEY}" = "" ]; then
  echo "⚠  WARNING: SUPABASE_ANON_KEY is not set."
fi

echo "✓ config.js written."
echo "✓ Build complete."
