#!/bin/bash
# ─── WaxLab build script ──────────────────────────────────────────────────────
# Runs on Netlify at deploy time. Does three things:
# 1. Writes Netlify environment variables into config.js
# 2. Downloads CDN dependencies and inlines them into index.html
#    so the deployed app works with ZERO network requests at runtime
# 3. Registers a service worker for offline caching after first load

set -e

echo "→ [1/3] Writing config.js from environment variables..."

cat > config.js << EOF
// Auto-generated by build.sh — do not edit manually.
window.WAXLAB_CONFIG = {
  SUPABASE_URL:      "${SUPABASE_URL:-}",
  SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY:-}",
  GOOGLE_CLIENT_ID:  "${GOOGLE_CLIENT_ID:-}"
};
EOF

if [ -z "${SUPABASE_URL}" ]; then
  echo "⚠  WARNING: SUPABASE_URL not set — app will run in local-only mode."
fi

echo "✓ config.js written."

# ─── Inline CDN scripts ───────────────────────────────────────────────────────
echo "→ [2/3] Downloading and inlining CDN dependencies..."

REACT_URL="https://unpkg.com/react@18/umd/react.production.min.js"
REACTDOM_URL="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"
SUPABASE_URL_CDN="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.js"
XLSX_URL="https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js"

download() {
  local url="$1" dest="$2" label="$3"
  if curl -sf --max-time 30 -o "$dest" "$url"; then
    echo "  ✓ $label ($(wc -c < "$dest" | tr -d ' ') bytes)"
  else
    echo "  ⚠  $label download failed — will use CDN fallback"
    echo "" > "$dest"   # empty file = fallback to original CDN tag
  fi
}

download "$REACT_URL"       "_react.js"    "React"
download "$REACTDOM_URL"    "_reactdom.js" "ReactDOM"
download "$SUPABASE_URL_CDN" "_supabase.js" "Supabase"
download "$XLSX_URL"        "_xlsx.js"     "XLSX"

# Python script to inline the downloaded JS into index.html
python3 << 'PYEOF'
import re, os

with open('index.html') as f:
    html = f.read()

replacements = [
    ('https://unpkg.com/react@18/umd/react.production.min.js',        '_react.js'),
    ('https://unpkg.com/react-dom@18/umd/react-dom.production.min.js','_reactdom.js'),
    ('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.js', '_supabase.js'),
    ('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js', '_xlsx.js'),
]

inlined = 0
for cdn_url, local_file in replacements:
    if not os.path.exists(local_file):
        continue
    with open(local_file) as f:
        js = f.read().strip()
    if not js:
        print(f"  ⚠  {local_file} empty, keeping CDN tag for {cdn_url}")
        continue
    old_tag = f'<script src="{cdn_url}"></script>'
    new_tag = f'<script>/* inlined: {cdn_url} */\n{js}\n</script>'
    if old_tag in html:
        html = html.replace(old_tag, new_tag)
        print(f"  ✓ Inlined {cdn_url.split('/')[-1]} ({len(js)//1024} KB)")
        inlined += 1

with open('index.html', 'w') as f:
    f.write(html)

print(f"  {inlined} of {len(replacements)} scripts inlined into index.html")
PYEOF

# Clean up temp files
rm -f _react.js _reactdom.js _supabase.js _xlsx.js

# ─── Service worker ───────────────────────────────────────────────────────────
echo "→ [3/3] Writing service worker for offline caching..."

CACHE_VERSION="waxlab-v$(date +%Y%m%d%H%M)"

cat > sw.js << SWEOF
// WaxLab Service Worker — offline-first cache
// Cache version: ${CACHE_VERSION}
const CACHE = "${CACHE_VERSION}";
const CORE = ["./", "./index.html", "./config.js"];

self.addEventListener("install", e => {
  e.waitUntil(
    caches.open(CACHE).then(c => c.addAll(CORE)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", e => {
  // Network-first for config.js (always get fresh credentials)
  // Cache-first for everything else (works offline)
  if (e.request.url.includes("config.js")) {
    e.respondWith(
      fetch(e.request).then(r => {
        const clone = r.clone();
        caches.open(CACHE).then(c => c.put(e.request, clone));
        return r;
      }).catch(() => caches.match(e.request))
    );
    return;
  }
  e.respondWith(
    caches.match(e.request).then(cached => {
      if (cached) return cached;
      return fetch(e.request).then(r => {
        if (r && r.status === 200 && r.type === "basic") {
          const clone = r.clone();
          caches.open(CACHE).then(c => c.put(e.request, clone));
        }
        return r;
      });
    })
  );
});
SWEOF

echo "✓ Service worker written (${CACHE_VERSION})"

# Inject service worker registration into index.html
python3 << 'PYEOF'
with open('index.html') as f:
    html = f.read()

sw_reg = """
<script>
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('./sw.js')
      .then(r => console.log('WaxLab SW registered'))
      .catch(e => console.warn('SW registration failed:', e));
  });
}
</script>"""

if 'serviceWorker' not in html:
    html = html.replace('</body>', sw_reg + '\n</body>')
    with open('index.html', 'w') as f:
        f.write(html)
    print("  ✓ Service worker registration injected into index.html")
else:
    print("  ✓ Service worker already registered")
PYEOF

echo ""
echo "✓ Build complete."
echo "  App is fully self-contained and works offline after first load."
